services:
  jumble:
    container_name: jumble-nginx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_PROXY_SERVER: ${JUMBLE_PROXY_SERVER_URL:-http://localhost:8090}
    ports:
      - "8089:80"
    restart: unless-stopped
    networks:
      - jumble

  proxy-server:
    image: ghcr.io/danvergara/jumble-proxy-server:latest
    environment:
      - ALLOW_ORIGIN=${JUMBLE_SOCIAL_URL:-http://localhost:8089}
      - JUMBLE_PROXY_GITHUB_TOKEN=${JUMBLE_PROXY_GITHUB_TOKEN}
      - ENABLE_PPROF=true
      - PORT=8080
    ports:
      - "8090:8080"
    networks:
      - jumble

  nostr-relay:
    image: scsibug/nostr-rs-relay:latest
    container_name: jumble-nostr-relay
    ports:
      - "7000:8080"
    environment:
      - RUST_LOG=warn,nostr_rs_relay=info
    volumes:
      - relay-data:/usr/src/app/db
    networks:
      - jumble
    restart: unless-stopped

volumes:
  relay-data:

networks:
  jumble:
